// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

package bilibili.app.view.v1;

/**
 * <pre>
 * 不喜欢原因
 * </pre>
 *
 * Protobuf type {@code bilibili.app.view.v1.Dislike}
 */
public final class Dislike extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.view.v1.Dislike)
    DislikeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Dislike.newBuilder() to construct.
  private Dislike(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Dislike() {
    title_ = "";
    subtitle_ = "";
    reasons_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Dislike();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_Dislike_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_Dislike_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.view.v1.Dislike.class, bilibili.app.view.v1.Dislike.Builder.class);
  }

  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBTITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subtitle_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string subtitle = 2;</code>
   * @return The subtitle.
   */
  @java.lang.Override
  public java.lang.String getSubtitle() {
    java.lang.Object ref = subtitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subtitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string subtitle = 2;</code>
   * @return The bytes for subtitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubtitleBytes() {
    java.lang.Object ref = subtitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subtitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REASONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<bilibili.app.view.v1.DislikeReasons> reasons_;
  /**
   * <pre>
   * 原因项列表
   * </pre>
   *
   * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
   */
  @java.lang.Override
  public java.util.List<bilibili.app.view.v1.DislikeReasons> getReasonsList() {
    return reasons_;
  }
  /**
   * <pre>
   * 原因项列表
   * </pre>
   *
   * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends bilibili.app.view.v1.DislikeReasonsOrBuilder> 
      getReasonsOrBuilderList() {
    return reasons_;
  }
  /**
   * <pre>
   * 原因项列表
   * </pre>
   *
   * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
   */
  @java.lang.Override
  public int getReasonsCount() {
    return reasons_.size();
  }
  /**
   * <pre>
   * 原因项列表
   * </pre>
   *
   * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
   */
  @java.lang.Override
  public bilibili.app.view.v1.DislikeReasons getReasons(int index) {
    return reasons_.get(index);
  }
  /**
   * <pre>
   * 原因项列表
   * </pre>
   *
   * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
   */
  @java.lang.Override
  public bilibili.app.view.v1.DislikeReasonsOrBuilder getReasonsOrBuilder(
      int index) {
    return reasons_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subtitle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subtitle_);
    }
    for (int i = 0; i < reasons_.size(); i++) {
      output.writeMessage(3, reasons_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subtitle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subtitle_);
    }
    for (int i = 0; i < reasons_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, reasons_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.view.v1.Dislike)) {
      return super.equals(obj);
    }
    bilibili.app.view.v1.Dislike other = (bilibili.app.view.v1.Dislike) obj;

    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getSubtitle()
        .equals(other.getSubtitle())) return false;
    if (!getReasonsList()
        .equals(other.getReasonsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + SUBTITLE_FIELD_NUMBER;
    hash = (53 * hash) + getSubtitle().hashCode();
    if (getReasonsCount() > 0) {
      hash = (37 * hash) + REASONS_FIELD_NUMBER;
      hash = (53 * hash) + getReasonsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.view.v1.Dislike parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.view.v1.Dislike parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bilibili.app.view.v1.Dislike parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.view.v1.Dislike parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.view.v1.Dislike prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 不喜欢原因
   * </pre>
   *
   * Protobuf type {@code bilibili.app.view.v1.Dislike}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.view.v1.Dislike)
      bilibili.app.view.v1.DislikeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_Dislike_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_Dislike_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.view.v1.Dislike.class, bilibili.app.view.v1.Dislike.Builder.class);
    }

    // Construct using bilibili.app.view.v1.Dislike.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      subtitle_ = "";
      if (reasonsBuilder_ == null) {
        reasons_ = java.util.Collections.emptyList();
      } else {
        reasons_ = null;
        reasonsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_Dislike_descriptor;
    }

    @java.lang.Override
    public bilibili.app.view.v1.Dislike getDefaultInstanceForType() {
      return bilibili.app.view.v1.Dislike.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.view.v1.Dislike build() {
      bilibili.app.view.v1.Dislike result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.view.v1.Dislike buildPartial() {
      bilibili.app.view.v1.Dislike result = new bilibili.app.view.v1.Dislike(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(bilibili.app.view.v1.Dislike result) {
      if (reasonsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          reasons_ = java.util.Collections.unmodifiableList(reasons_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.reasons_ = reasons_;
      } else {
        result.reasons_ = reasonsBuilder_.build();
      }
    }

    private void buildPartial0(bilibili.app.view.v1.Dislike result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.subtitle_ = subtitle_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.view.v1.Dislike) {
        return mergeFrom((bilibili.app.view.v1.Dislike)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.view.v1.Dislike other) {
      if (other == bilibili.app.view.v1.Dislike.getDefaultInstance()) return this;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSubtitle().isEmpty()) {
        subtitle_ = other.subtitle_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (reasonsBuilder_ == null) {
        if (!other.reasons_.isEmpty()) {
          if (reasons_.isEmpty()) {
            reasons_ = other.reasons_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReasonsIsMutable();
            reasons_.addAll(other.reasons_);
          }
          onChanged();
        }
      } else {
        if (!other.reasons_.isEmpty()) {
          if (reasonsBuilder_.isEmpty()) {
            reasonsBuilder_.dispose();
            reasonsBuilder_ = null;
            reasons_ = other.reasons_;
            bitField0_ = (bitField0_ & ~0x00000004);
            reasonsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReasonsFieldBuilder() : null;
          } else {
            reasonsBuilder_.addAllMessages(other.reasons_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              subtitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              bilibili.app.view.v1.DislikeReasons m =
                  input.readMessage(
                      bilibili.app.view.v1.DislikeReasons.parser(),
                      extensionRegistry);
              if (reasonsBuilder_ == null) {
                ensureReasonsIsMutable();
                reasons_.add(m);
              } else {
                reasonsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object subtitle_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string subtitle = 2;</code>
     * @return The subtitle.
     */
    public java.lang.String getSubtitle() {
      java.lang.Object ref = subtitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subtitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string subtitle = 2;</code>
     * @return The bytes for subtitle.
     */
    public com.google.protobuf.ByteString
        getSubtitleBytes() {
      java.lang.Object ref = subtitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subtitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string subtitle = 2;</code>
     * @param value The subtitle to set.
     * @return This builder for chaining.
     */
    public Builder setSubtitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subtitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string subtitle = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubtitle() {
      subtitle_ = getDefaultInstance().getSubtitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string subtitle = 2;</code>
     * @param value The bytes for subtitle to set.
     * @return This builder for chaining.
     */
    public Builder setSubtitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subtitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<bilibili.app.view.v1.DislikeReasons> reasons_ =
      java.util.Collections.emptyList();
    private void ensureReasonsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        reasons_ = new java.util.ArrayList<bilibili.app.view.v1.DislikeReasons>(reasons_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bilibili.app.view.v1.DislikeReasons, bilibili.app.view.v1.DislikeReasons.Builder, bilibili.app.view.v1.DislikeReasonsOrBuilder> reasonsBuilder_;

    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public java.util.List<bilibili.app.view.v1.DislikeReasons> getReasonsList() {
      if (reasonsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reasons_);
      } else {
        return reasonsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public int getReasonsCount() {
      if (reasonsBuilder_ == null) {
        return reasons_.size();
      } else {
        return reasonsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public bilibili.app.view.v1.DislikeReasons getReasons(int index) {
      if (reasonsBuilder_ == null) {
        return reasons_.get(index);
      } else {
        return reasonsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder setReasons(
        int index, bilibili.app.view.v1.DislikeReasons value) {
      if (reasonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReasonsIsMutable();
        reasons_.set(index, value);
        onChanged();
      } else {
        reasonsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder setReasons(
        int index, bilibili.app.view.v1.DislikeReasons.Builder builderForValue) {
      if (reasonsBuilder_ == null) {
        ensureReasonsIsMutable();
        reasons_.set(index, builderForValue.build());
        onChanged();
      } else {
        reasonsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder addReasons(bilibili.app.view.v1.DislikeReasons value) {
      if (reasonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReasonsIsMutable();
        reasons_.add(value);
        onChanged();
      } else {
        reasonsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder addReasons(
        int index, bilibili.app.view.v1.DislikeReasons value) {
      if (reasonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReasonsIsMutable();
        reasons_.add(index, value);
        onChanged();
      } else {
        reasonsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder addReasons(
        bilibili.app.view.v1.DislikeReasons.Builder builderForValue) {
      if (reasonsBuilder_ == null) {
        ensureReasonsIsMutable();
        reasons_.add(builderForValue.build());
        onChanged();
      } else {
        reasonsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder addReasons(
        int index, bilibili.app.view.v1.DislikeReasons.Builder builderForValue) {
      if (reasonsBuilder_ == null) {
        ensureReasonsIsMutable();
        reasons_.add(index, builderForValue.build());
        onChanged();
      } else {
        reasonsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder addAllReasons(
        java.lang.Iterable<? extends bilibili.app.view.v1.DislikeReasons> values) {
      if (reasonsBuilder_ == null) {
        ensureReasonsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reasons_);
        onChanged();
      } else {
        reasonsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder clearReasons() {
      if (reasonsBuilder_ == null) {
        reasons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        reasonsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public Builder removeReasons(int index) {
      if (reasonsBuilder_ == null) {
        ensureReasonsIsMutable();
        reasons_.remove(index);
        onChanged();
      } else {
        reasonsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public bilibili.app.view.v1.DislikeReasons.Builder getReasonsBuilder(
        int index) {
      return getReasonsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public bilibili.app.view.v1.DislikeReasonsOrBuilder getReasonsOrBuilder(
        int index) {
      if (reasonsBuilder_ == null) {
        return reasons_.get(index);  } else {
        return reasonsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public java.util.List<? extends bilibili.app.view.v1.DislikeReasonsOrBuilder> 
         getReasonsOrBuilderList() {
      if (reasonsBuilder_ != null) {
        return reasonsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reasons_);
      }
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public bilibili.app.view.v1.DislikeReasons.Builder addReasonsBuilder() {
      return getReasonsFieldBuilder().addBuilder(
          bilibili.app.view.v1.DislikeReasons.getDefaultInstance());
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public bilibili.app.view.v1.DislikeReasons.Builder addReasonsBuilder(
        int index) {
      return getReasonsFieldBuilder().addBuilder(
          index, bilibili.app.view.v1.DislikeReasons.getDefaultInstance());
    }
    /**
     * <pre>
     * 原因项列表
     * </pre>
     *
     * <code>repeated .bilibili.app.view.v1.DislikeReasons reasons = 3;</code>
     */
    public java.util.List<bilibili.app.view.v1.DislikeReasons.Builder> 
         getReasonsBuilderList() {
      return getReasonsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bilibili.app.view.v1.DislikeReasons, bilibili.app.view.v1.DislikeReasons.Builder, bilibili.app.view.v1.DislikeReasonsOrBuilder> 
        getReasonsFieldBuilder() {
      if (reasonsBuilder_ == null) {
        reasonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bilibili.app.view.v1.DislikeReasons, bilibili.app.view.v1.DislikeReasons.Builder, bilibili.app.view.v1.DislikeReasonsOrBuilder>(
                reasons_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        reasons_ = null;
      }
      return reasonsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.view.v1.Dislike)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.view.v1.Dislike)
  private static final bilibili.app.view.v1.Dislike DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.view.v1.Dislike();
  }

  public static bilibili.app.view.v1.Dislike getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dislike>
      PARSER = new com.google.protobuf.AbstractParser<Dislike>() {
    @java.lang.Override
    public Dislike parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Dislike> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dislike> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.view.v1.Dislike getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

