// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/search/v2/search.proto

package bilibili.app.search.v2;

public interface SearchEggReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.search.v2.SearchEggReq)
    com.google.protobuf.MessageOrBuilder {
}
