// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v2/playurl.proto

package bilibili.pgc.gateway.player.v2;

public interface CouponInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.pgc.gateway.player.v2.CouponInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 提示框信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.CouponToast toast = 1;</code>
   * @return Whether the toast field is set.
   */
  boolean hasToast();
  /**
   * <pre>
   * 提示框信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.CouponToast toast = 1;</code>
   * @return The toast.
   */
  bilibili.pgc.gateway.player.v2.CouponToast getToast();
  /**
   * <pre>
   * 提示框信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.CouponToast toast = 1;</code>
   */
  bilibili.pgc.gateway.player.v2.CouponToastOrBuilder getToastOrBuilder();

  /**
   * <pre>
   * 弹窗信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.PopWin pop_win = 2;</code>
   * @return Whether the popWin field is set.
   */
  boolean hasPopWin();
  /**
   * <pre>
   * 弹窗信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.PopWin pop_win = 2;</code>
   * @return The popWin.
   */
  bilibili.pgc.gateway.player.v2.PopWin getPopWin();
  /**
   * <pre>
   * 弹窗信息
   * </pre>
   *
   * <code>.bilibili.pgc.gateway.player.v2.PopWin pop_win = 2;</code>
   */
  bilibili.pgc.gateway.player.v2.PopWinOrBuilder getPopWinOrBuilder();
}
