// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package bilibili.app.dynamic.v1;

/**
 * <pre>
 * 播放器模块
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v1.SVideoModulePlayer}
 */
public final class SVideoModulePlayer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v1.SVideoModulePlayer)
    SVideoModulePlayerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SVideoModulePlayer.newBuilder() to construct.
  private SVideoModulePlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SVideoModulePlayer() {
    title_ = "";
    cover_ = "";
    uri_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SVideoModulePlayer();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.dynamic.v1.DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoModulePlayer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.dynamic.v1.DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoModulePlayer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.dynamic.v1.SVideoModulePlayer.class, bilibili.app.dynamic.v1.SVideoModulePlayer.Builder.class);
  }

  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cover_ = "";
  /**
   * <pre>
   * 封面图
   * </pre>
   *
   * <code>string cover = 2;</code>
   * @return The cover.
   */
  @java.lang.Override
  public java.lang.String getCover() {
    java.lang.Object ref = cover_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cover_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 封面图
   * </pre>
   *
   * <code>string cover = 2;</code>
   * @return The bytes for cover.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoverBytes() {
    java.lang.Object ref = cover_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cover_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URI_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uri_ = "";
  /**
   * <pre>
   * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
   * </pre>
   *
   * <code>string uri = 3;</code>
   * @return The uri.
   */
  @java.lang.Override
  public java.lang.String getUri() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
   * </pre>
   *
   * <code>string uri = 3;</code>
   * @return The bytes for uri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUriBytes() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AID_FIELD_NUMBER = 4;
  private long aid_ = 0L;
  /**
   * <pre>
   * aid
   * </pre>
   *
   * <code>int64 aid = 4;</code>
   * @return The aid.
   */
  @java.lang.Override
  public long getAid() {
    return aid_;
  }

  public static final int CID_FIELD_NUMBER = 5;
  private long cid_ = 0L;
  /**
   * <pre>
   * cid
   * </pre>
   *
   * <code>int64 cid = 5;</code>
   * @return The cid.
   */
  @java.lang.Override
  public long getCid() {
    return cid_;
  }

  public static final int DURATION_FIELD_NUMBER = 6;
  private long duration_ = 0L;
  /**
   * <pre>
   * 视频时长
   * </pre>
   *
   * <code>int64 duration = 6;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }

  public static final int DIMENSION_FIELD_NUMBER = 7;
  private bilibili.app.dynamic.v1.Dimension dimension_;
  /**
   * <pre>
   * 尺寸信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
   * @return Whether the dimension field is set.
   */
  @java.lang.Override
  public boolean hasDimension() {
    return dimension_ != null;
  }
  /**
   * <pre>
   * 尺寸信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
   * @return The dimension.
   */
  @java.lang.Override
  public bilibili.app.dynamic.v1.Dimension getDimension() {
    return dimension_ == null ? bilibili.app.dynamic.v1.Dimension.getDefaultInstance() : dimension_;
  }
  /**
   * <pre>
   * 尺寸信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
   */
  @java.lang.Override
  public bilibili.app.dynamic.v1.DimensionOrBuilder getDimensionOrBuilder() {
    return dimension_ == null ? bilibili.app.dynamic.v1.Dimension.getDefaultInstance() : dimension_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cover_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
    }
    if (aid_ != 0L) {
      output.writeInt64(4, aid_);
    }
    if (cid_ != 0L) {
      output.writeInt64(5, cid_);
    }
    if (duration_ != 0L) {
      output.writeInt64(6, duration_);
    }
    if (dimension_ != null) {
      output.writeMessage(7, getDimension());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cover_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
    }
    if (aid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, aid_);
    }
    if (cid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, cid_);
    }
    if (duration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, duration_);
    }
    if (dimension_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDimension());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.dynamic.v1.SVideoModulePlayer)) {
      return super.equals(obj);
    }
    bilibili.app.dynamic.v1.SVideoModulePlayer other = (bilibili.app.dynamic.v1.SVideoModulePlayer) obj;

    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getCover()
        .equals(other.getCover())) return false;
    if (!getUri()
        .equals(other.getUri())) return false;
    if (getAid()
        != other.getAid()) return false;
    if (getCid()
        != other.getCid()) return false;
    if (getDuration()
        != other.getDuration()) return false;
    if (hasDimension() != other.hasDimension()) return false;
    if (hasDimension()) {
      if (!getDimension()
          .equals(other.getDimension())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + COVER_FIELD_NUMBER;
    hash = (53 * hash) + getCover().hashCode();
    hash = (37 * hash) + URI_FIELD_NUMBER;
    hash = (53 * hash) + getUri().hashCode();
    hash = (37 * hash) + AID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAid());
    hash = (37 * hash) + CID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCid());
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDuration());
    if (hasDimension()) {
      hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
      hash = (53 * hash) + getDimension().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.dynamic.v1.SVideoModulePlayer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.dynamic.v1.SVideoModulePlayer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 播放器模块
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v1.SVideoModulePlayer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v1.SVideoModulePlayer)
      bilibili.app.dynamic.v1.SVideoModulePlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.dynamic.v1.DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoModulePlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.dynamic.v1.DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoModulePlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.dynamic.v1.SVideoModulePlayer.class, bilibili.app.dynamic.v1.SVideoModulePlayer.Builder.class);
    }

    // Construct using bilibili.app.dynamic.v1.SVideoModulePlayer.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      cover_ = "";
      uri_ = "";
      aid_ = 0L;
      cid_ = 0L;
      duration_ = 0L;
      dimension_ = null;
      if (dimensionBuilder_ != null) {
        dimensionBuilder_.dispose();
        dimensionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.dynamic.v1.DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoModulePlayer_descriptor;
    }

    @java.lang.Override
    public bilibili.app.dynamic.v1.SVideoModulePlayer getDefaultInstanceForType() {
      return bilibili.app.dynamic.v1.SVideoModulePlayer.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.dynamic.v1.SVideoModulePlayer build() {
      bilibili.app.dynamic.v1.SVideoModulePlayer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.dynamic.v1.SVideoModulePlayer buildPartial() {
      bilibili.app.dynamic.v1.SVideoModulePlayer result = new bilibili.app.dynamic.v1.SVideoModulePlayer(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.dynamic.v1.SVideoModulePlayer result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cover_ = cover_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.uri_ = uri_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.aid_ = aid_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.cid_ = cid_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.dimension_ = dimensionBuilder_ == null
            ? dimension_
            : dimensionBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.dynamic.v1.SVideoModulePlayer) {
        return mergeFrom((bilibili.app.dynamic.v1.SVideoModulePlayer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.dynamic.v1.SVideoModulePlayer other) {
      if (other == bilibili.app.dynamic.v1.SVideoModulePlayer.getDefaultInstance()) return this;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCover().isEmpty()) {
        cover_ = other.cover_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getUri().isEmpty()) {
        uri_ = other.uri_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getAid() != 0L) {
        setAid(other.getAid());
      }
      if (other.getCid() != 0L) {
        setCid(other.getCid());
      }
      if (other.getDuration() != 0L) {
        setDuration(other.getDuration());
      }
      if (other.hasDimension()) {
        mergeDimension(other.getDimension());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              cover_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              uri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              aid_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              cid_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              duration_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  getDimensionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object cover_ = "";
    /**
     * <pre>
     * 封面图
     * </pre>
     *
     * <code>string cover = 2;</code>
     * @return The cover.
     */
    public java.lang.String getCover() {
      java.lang.Object ref = cover_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cover_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 封面图
     * </pre>
     *
     * <code>string cover = 2;</code>
     * @return The bytes for cover.
     */
    public com.google.protobuf.ByteString
        getCoverBytes() {
      java.lang.Object ref = cover_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cover_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 封面图
     * </pre>
     *
     * <code>string cover = 2;</code>
     * @param value The cover to set.
     * @return This builder for chaining.
     */
    public Builder setCover(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cover_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图
     * </pre>
     *
     * <code>string cover = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCover() {
      cover_ = getDefaultInstance().getCover();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图
     * </pre>
     *
     * <code>string cover = 2;</code>
     * @param value The bytes for cover to set.
     * @return This builder for chaining.
     */
    public Builder setCoverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cover_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object uri_ = "";
    /**
     * <pre>
     * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The uri.
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The bytes for uri.
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uri_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      uri_ = getDefaultInstance().getUri();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转地址，秒开地址如果有会拼接player_preload可参考天马
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uri_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long aid_ ;
    /**
     * <pre>
     * aid
     * </pre>
     *
     * <code>int64 aid = 4;</code>
     * @return The aid.
     */
    @java.lang.Override
    public long getAid() {
      return aid_;
    }
    /**
     * <pre>
     * aid
     * </pre>
     *
     * <code>int64 aid = 4;</code>
     * @param value The aid to set.
     * @return This builder for chaining.
     */
    public Builder setAid(long value) {

      aid_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * aid
     * </pre>
     *
     * <code>int64 aid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      aid_ = 0L;
      onChanged();
      return this;
    }

    private long cid_ ;
    /**
     * <pre>
     * cid
     * </pre>
     *
     * <code>int64 cid = 5;</code>
     * @return The cid.
     */
    @java.lang.Override
    public long getCid() {
      return cid_;
    }
    /**
     * <pre>
     * cid
     * </pre>
     *
     * <code>int64 cid = 5;</code>
     * @param value The cid to set.
     * @return This builder for chaining.
     */
    public Builder setCid(long value) {

      cid_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cid
     * </pre>
     *
     * <code>int64 cid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCid() {
      bitField0_ = (bitField0_ & ~0x00000010);
      cid_ = 0L;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <pre>
     * 视频时长
     * </pre>
     *
     * <code>int64 duration = 6;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return duration_;
    }
    /**
     * <pre>
     * 视频时长
     * </pre>
     *
     * <code>int64 duration = 6;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {

      duration_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频时长
     * </pre>
     *
     * <code>int64 duration = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      duration_ = 0L;
      onChanged();
      return this;
    }

    private bilibili.app.dynamic.v1.Dimension dimension_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.dynamic.v1.Dimension, bilibili.app.dynamic.v1.Dimension.Builder, bilibili.app.dynamic.v1.DimensionOrBuilder> dimensionBuilder_;
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     * @return Whether the dimension field is set.
     */
    public boolean hasDimension() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     * @return The dimension.
     */
    public bilibili.app.dynamic.v1.Dimension getDimension() {
      if (dimensionBuilder_ == null) {
        return dimension_ == null ? bilibili.app.dynamic.v1.Dimension.getDefaultInstance() : dimension_;
      } else {
        return dimensionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public Builder setDimension(bilibili.app.dynamic.v1.Dimension value) {
      if (dimensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dimension_ = value;
      } else {
        dimensionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public Builder setDimension(
        bilibili.app.dynamic.v1.Dimension.Builder builderForValue) {
      if (dimensionBuilder_ == null) {
        dimension_ = builderForValue.build();
      } else {
        dimensionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public Builder mergeDimension(bilibili.app.dynamic.v1.Dimension value) {
      if (dimensionBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          dimension_ != null &&
          dimension_ != bilibili.app.dynamic.v1.Dimension.getDefaultInstance()) {
          getDimensionBuilder().mergeFrom(value);
        } else {
          dimension_ = value;
        }
      } else {
        dimensionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public Builder clearDimension() {
      bitField0_ = (bitField0_ & ~0x00000040);
      dimension_ = null;
      if (dimensionBuilder_ != null) {
        dimensionBuilder_.dispose();
        dimensionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public bilibili.app.dynamic.v1.Dimension.Builder getDimensionBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getDimensionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    public bilibili.app.dynamic.v1.DimensionOrBuilder getDimensionOrBuilder() {
      if (dimensionBuilder_ != null) {
        return dimensionBuilder_.getMessageOrBuilder();
      } else {
        return dimension_ == null ?
            bilibili.app.dynamic.v1.Dimension.getDefaultInstance() : dimension_;
      }
    }
    /**
     * <pre>
     * 尺寸信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.Dimension dimension = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.dynamic.v1.Dimension, bilibili.app.dynamic.v1.Dimension.Builder, bilibili.app.dynamic.v1.DimensionOrBuilder> 
        getDimensionFieldBuilder() {
      if (dimensionBuilder_ == null) {
        dimensionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.dynamic.v1.Dimension, bilibili.app.dynamic.v1.Dimension.Builder, bilibili.app.dynamic.v1.DimensionOrBuilder>(
                getDimension(),
                getParentForChildren(),
                isClean());
        dimension_ = null;
      }
      return dimensionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v1.SVideoModulePlayer)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v1.SVideoModulePlayer)
  private static final bilibili.app.dynamic.v1.SVideoModulePlayer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.dynamic.v1.SVideoModulePlayer();
  }

  public static bilibili.app.dynamic.v1.SVideoModulePlayer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SVideoModulePlayer>
      PARSER = new com.google.protobuf.AbstractParser<SVideoModulePlayer>() {
    @java.lang.Override
    public SVideoModulePlayer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SVideoModulePlayer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SVideoModulePlayer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.dynamic.v1.SVideoModulePlayer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

