// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package bilibili.app.dynamic.v2;

public interface CampusMngSloganOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v2.CampusMngSlogan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string slogan = 2;</code>
   * @return The slogan.
   */
  java.lang.String getSlogan();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string slogan = 2;</code>
   * @return The bytes for slogan.
   */
  com.google.protobuf.ByteString
      getSloganBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string input_hint_msg = 3;</code>
   * @return The inputHintMsg.
   */
  java.lang.String getInputHintMsg();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string input_hint_msg = 3;</code>
   * @return The bytes for inputHintMsg.
   */
  com.google.protobuf.ByteString
      getInputHintMsgBytes();
}
