// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package bilibili.app.dynamic.v2;

public interface ModuleNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v2.ModuleNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string identity = 1;</code>
   * @return The identity.
   */
  java.lang.String getIdentity();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string identity = 1;</code>
   * @return The bytes for identity.
   */
  com.google.protobuf.ByteString
      getIdentityBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string icon = 2;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string icon = 2;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string url = 4;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>string url = 4;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 notice_type = 5;</code>
   * @return The noticeType.
   */
  int getNoticeType();
}
