// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/broadcast/message/ticket/activitygame.proto

package bilibili.broadcast.message.ticket;

public final class ActivitygameRpcProto {
  private ActivitygameRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf enum {@code bilibili.broadcast.message.ticket.RoomStatus}
   */
  public enum RoomStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 暂停:
     * </pre>
     *
     * <code>Pause = 0;</code>
     */
    Pause(0),
    /**
     * <pre>
     * 播放:
     * </pre>
     *
     * <code>Play = 1;</code>
     */
    Play(1),
    /**
     * <pre>
     * 终止:
     * </pre>
     *
     * <code>End = 2;</code>
     */
    End(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 暂停:
     * </pre>
     *
     * <code>Pause = 0;</code>
     */
    public static final int Pause_VALUE = 0;
    /**
     * <pre>
     * 播放:
     * </pre>
     *
     * <code>Play = 1;</code>
     */
    public static final int Play_VALUE = 1;
    /**
     * <pre>
     * 终止:
     * </pre>
     *
     * <code>End = 2;</code>
     */
    public static final int End_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RoomStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RoomStatus forNumber(int value) {
      switch (value) {
        case 0: return Pause;
        case 1: return Play;
        case 2: return End;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoomStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoomStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoomStatus>() {
            public RoomStatus findValueByNumber(int number) {
              return RoomStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return bilibili.broadcast.message.ticket.ActivitygameRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RoomStatus[] VALUES = values();

    public static RoomStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RoomStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:bilibili.broadcast.message.ticket.RoomStatus)
  }

  public interface RoomEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.broadcast.message.ticket.RoomEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * RoomStatus 类型
     * </pre>
     *
     * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
     * @return The enum numeric value on the wire for roomStatus.
     */
    int getRoomStatusValue();
    /**
     * <pre>
     * RoomStatus 类型
     * </pre>
     *
     * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
     * @return The roomStatus.
     */
    bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus getRoomStatus();

    /**
     * <pre>
     * </pre>
     *
     * <code>string room_message = 2;</code>
     * @return The roomMessage.
     */
    java.lang.String getRoomMessage();
    /**
     * <pre>
     * </pre>
     *
     * <code>string room_message = 2;</code>
     * @return The bytes for roomMessage.
     */
    com.google.protobuf.ByteString
        getRoomMessageBytes();
  }
  /**
   * <pre>
   * 推送选项
   * </pre>
   *
   * Protobuf type {@code bilibili.broadcast.message.ticket.RoomEvent}
   */
  public static final class RoomEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.broadcast.message.ticket.RoomEvent)
      RoomEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomEvent.newBuilder() to construct.
    private RoomEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomEvent() {
      roomStatus_ = 0;
      roomMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoomEvent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.broadcast.message.ticket.ActivitygameRpcProto.internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.broadcast.message.ticket.ActivitygameRpcProto.internal_static_bilibili_broadcast_message_ticket_RoomEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.class, bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.Builder.class);
    }

    public static final int ROOM_STATUS_FIELD_NUMBER = 1;
    private int roomStatus_ = 0;
    /**
     * <pre>
     * RoomStatus 类型
     * </pre>
     *
     * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
     * @return The enum numeric value on the wire for roomStatus.
     */
    @java.lang.Override public int getRoomStatusValue() {
      return roomStatus_;
    }
    /**
     * <pre>
     * RoomStatus 类型
     * </pre>
     *
     * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
     * @return The roomStatus.
     */
    @java.lang.Override public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus getRoomStatus() {
      bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus result = bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.forNumber(roomStatus_);
      return result == null ? bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.UNRECOGNIZED : result;
    }

    public static final int ROOM_MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object roomMessage_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string room_message = 2;</code>
     * @return The roomMessage.
     */
    @java.lang.Override
    public java.lang.String getRoomMessage() {
      java.lang.Object ref = roomMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string room_message = 2;</code>
     * @return The bytes for roomMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomMessageBytes() {
      java.lang.Object ref = roomMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomStatus_ != bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.Pause.getNumber()) {
        output.writeEnum(1, roomStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomMessage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomStatus_ != bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.Pause.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, roomStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomMessage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent)) {
        return super.equals(obj);
      }
      bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent other = (bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent) obj;

      if (roomStatus_ != other.roomStatus_) return false;
      if (!getRoomMessage()
          .equals(other.getRoomMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOM_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + roomStatus_;
      hash = (37 * hash) + ROOM_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRoomMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 推送选项
     * </pre>
     *
     * Protobuf type {@code bilibili.broadcast.message.ticket.RoomEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.broadcast.message.ticket.RoomEvent)
        bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.broadcast.message.ticket.ActivitygameRpcProto.internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.broadcast.message.ticket.ActivitygameRpcProto.internal_static_bilibili_broadcast_message_ticket_RoomEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.class, bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.Builder.class);
      }

      // Construct using bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        roomStatus_ = 0;
        roomMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.broadcast.message.ticket.ActivitygameRpcProto.internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor;
      }

      @java.lang.Override
      public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent getDefaultInstanceForType() {
        return bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent build() {
        bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent buildPartial() {
        bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent result = new bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.roomStatus_ = roomStatus_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.roomMessage_ = roomMessage_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent) {
          return mergeFrom((bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent other) {
        if (other == bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent.getDefaultInstance()) return this;
        if (other.roomStatus_ != 0) {
          setRoomStatusValue(other.getRoomStatusValue());
        }
        if (!other.getRoomMessage().isEmpty()) {
          roomMessage_ = other.roomMessage_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                roomStatus_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                roomMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int roomStatus_ = 0;
      /**
       * <pre>
       * RoomStatus 类型
       * </pre>
       *
       * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
       * @return The enum numeric value on the wire for roomStatus.
       */
      @java.lang.Override public int getRoomStatusValue() {
        return roomStatus_;
      }
      /**
       * <pre>
       * RoomStatus 类型
       * </pre>
       *
       * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
       * @param value The enum numeric value on the wire for roomStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRoomStatusValue(int value) {
        roomStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RoomStatus 类型
       * </pre>
       *
       * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
       * @return The roomStatus.
       */
      @java.lang.Override
      public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus getRoomStatus() {
        bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus result = bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.forNumber(roomStatus_);
        return result == null ? bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * RoomStatus 类型
       * </pre>
       *
       * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
       * @param value The roomStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRoomStatus(bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        roomStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RoomStatus 类型
       * </pre>
       *
       * <code>.bilibili.broadcast.message.ticket.RoomStatus room_status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roomMessage_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string room_message = 2;</code>
       * @return The roomMessage.
       */
      public java.lang.String getRoomMessage() {
        java.lang.Object ref = roomMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string room_message = 2;</code>
       * @return The bytes for roomMessage.
       */
      public com.google.protobuf.ByteString
          getRoomMessageBytes() {
        java.lang.Object ref = roomMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string room_message = 2;</code>
       * @param value The roomMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRoomMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        roomMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string room_message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomMessage() {
        roomMessage_ = getDefaultInstance().getRoomMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string room_message = 2;</code>
       * @param value The bytes for roomMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRoomMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        roomMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.broadcast.message.ticket.RoomEvent)
    }

    // @@protoc_insertion_point(class_scope:bilibili.broadcast.message.ticket.RoomEvent)
    private static final bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent();
    }

    public static bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomEvent>
        PARSER = new com.google.protobuf.AbstractParser<RoomEvent>() {
      @java.lang.Override
      public RoomEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RoomEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.broadcast.message.ticket.ActivitygameRpcProto.RoomEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_broadcast_message_ticket_RoomEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4bilibili/broadcast/message/ticket/acti" +
      "vitygame.proto\022!bilibili.broadcast.messa" +
      "ge.ticket\"e\n\tRoomEvent\022B\n\013room_status\030\001 " +
      "\001(\0162-.bilibili.broadcast.message.ticket." +
      "RoomStatus\022\024\n\014room_message\030\002 \001(\t**\n\nRoom" +
      "Status\022\t\n\005Pause\020\000\022\010\n\004Play\020\001\022\007\n\003End\020\002B\030B\024" +
      "ActivitygameRpcProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_broadcast_message_ticket_RoomEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_broadcast_message_ticket_RoomEvent_descriptor,
        new java.lang.String[] { "RoomStatus", "RoomMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
