// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/playeronline/v1/playeronline.proto

package bilibili.app.playeronline.v1;

/**
 * <pre>
 * 获取在线人数-回复
 * </pre>
 *
 * Protobuf type {@code bilibili.app.playeronline.v1.PlayerOnlineReply}
 */
public final class PlayerOnlineReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.playeronline.v1.PlayerOnlineReply)
    PlayerOnlineReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerOnlineReply.newBuilder() to construct.
  private PlayerOnlineReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerOnlineReply() {
    totalText_ = "";
    sdmText_ = "";
    totalNumberText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerOnlineReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.playeronline.v1.Playeronline.internal_static_bilibili_app_playeronline_v1_PlayerOnlineReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.playeronline.v1.Playeronline.internal_static_bilibili_app_playeronline_v1_PlayerOnlineReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.playeronline.v1.PlayerOnlineReply.class, bilibili.app.playeronline.v1.PlayerOnlineReply.Builder.class);
  }

  public static final int TOTAL_TEXT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object totalText_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string total_text = 1;</code>
   * @return The totalText.
   */
  @java.lang.Override
  public java.lang.String getTotalText() {
    java.lang.Object ref = totalText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string total_text = 1;</code>
   * @return The bytes for totalText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTotalTextBytes() {
    java.lang.Object ref = totalText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEC_NEXT_FIELD_NUMBER = 2;
  private long secNext_ = 0L;
  /**
   * <pre>
   * 下次轮询间隔时间
   * </pre>
   *
   * <code>int64 sec_next = 2;</code>
   * @return The secNext.
   */
  @java.lang.Override
  public long getSecNext() {
    return secNext_;
  }

  public static final int BOTTOM_SHOW_FIELD_NUMBER = 3;
  private boolean bottomShow_ = false;
  /**
   * <pre>
   * 是否底部显示
   * </pre>
   *
   * <code>bool bottom_show = 3;</code>
   * @return The bottomShow.
   */
  @java.lang.Override
  public boolean getBottomShow() {
    return bottomShow_;
  }

  public static final int SDM_SHOW_FIELD_NUMBER = 4;
  private boolean sdmShow_ = false;
  /**
   * <pre>
   * </pre>
   *
   * <code>bool sdm_show = 4;</code>
   * @return The sdmShow.
   */
  @java.lang.Override
  public boolean getSdmShow() {
    return sdmShow_;
  }

  public static final int SDM_TEXT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sdmText_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string sdm_text = 5;</code>
   * @return The sdmText.
   */
  @java.lang.Override
  public java.lang.String getSdmText() {
    java.lang.Object ref = sdmText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sdmText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string sdm_text = 5;</code>
   * @return The bytes for sdmText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSdmTextBytes() {
    java.lang.Object ref = sdmText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sdmText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_NUMBER_FIELD_NUMBER = 6;
  private long totalNumber_ = 0L;
  /**
   * <pre>
   * </pre>
   *
   * <code>int64 total_number = 6;</code>
   * @return The totalNumber.
   */
  @java.lang.Override
  public long getTotalNumber() {
    return totalNumber_;
  }

  public static final int TOTAL_NUMBER_TEXT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object totalNumberText_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string total_number_text = 7;</code>
   * @return The totalNumberText.
   */
  @java.lang.Override
  public java.lang.String getTotalNumberText() {
    java.lang.Object ref = totalNumberText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalNumberText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string total_number_text = 7;</code>
   * @return The bytes for totalNumberText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTotalNumberTextBytes() {
    java.lang.Object ref = totalNumberText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalNumberText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(totalText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, totalText_);
    }
    if (secNext_ != 0L) {
      output.writeInt64(2, secNext_);
    }
    if (bottomShow_ != false) {
      output.writeBool(3, bottomShow_);
    }
    if (sdmShow_ != false) {
      output.writeBool(4, sdmShow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdmText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sdmText_);
    }
    if (totalNumber_ != 0L) {
      output.writeInt64(6, totalNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(totalNumberText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, totalNumberText_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(totalText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, totalText_);
    }
    if (secNext_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, secNext_);
    }
    if (bottomShow_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, bottomShow_);
    }
    if (sdmShow_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, sdmShow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdmText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sdmText_);
    }
    if (totalNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, totalNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(totalNumberText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, totalNumberText_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.playeronline.v1.PlayerOnlineReply)) {
      return super.equals(obj);
    }
    bilibili.app.playeronline.v1.PlayerOnlineReply other = (bilibili.app.playeronline.v1.PlayerOnlineReply) obj;

    if (!getTotalText()
        .equals(other.getTotalText())) return false;
    if (getSecNext()
        != other.getSecNext()) return false;
    if (getBottomShow()
        != other.getBottomShow()) return false;
    if (getSdmShow()
        != other.getSdmShow()) return false;
    if (!getSdmText()
        .equals(other.getSdmText())) return false;
    if (getTotalNumber()
        != other.getTotalNumber()) return false;
    if (!getTotalNumberText()
        .equals(other.getTotalNumberText())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalText().hashCode();
    hash = (37 * hash) + SEC_NEXT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSecNext());
    hash = (37 * hash) + BOTTOM_SHOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBottomShow());
    hash = (37 * hash) + SDM_SHOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSdmShow());
    hash = (37 * hash) + SDM_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getSdmText().hashCode();
    hash = (37 * hash) + TOTAL_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalNumber());
    hash = (37 * hash) + TOTAL_NUMBER_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalNumberText().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.playeronline.v1.PlayerOnlineReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.playeronline.v1.PlayerOnlineReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取在线人数-回复
   * </pre>
   *
   * Protobuf type {@code bilibili.app.playeronline.v1.PlayerOnlineReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.playeronline.v1.PlayerOnlineReply)
      bilibili.app.playeronline.v1.PlayerOnlineReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.playeronline.v1.Playeronline.internal_static_bilibili_app_playeronline_v1_PlayerOnlineReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.playeronline.v1.Playeronline.internal_static_bilibili_app_playeronline_v1_PlayerOnlineReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.playeronline.v1.PlayerOnlineReply.class, bilibili.app.playeronline.v1.PlayerOnlineReply.Builder.class);
    }

    // Construct using bilibili.app.playeronline.v1.PlayerOnlineReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalText_ = "";
      secNext_ = 0L;
      bottomShow_ = false;
      sdmShow_ = false;
      sdmText_ = "";
      totalNumber_ = 0L;
      totalNumberText_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.playeronline.v1.Playeronline.internal_static_bilibili_app_playeronline_v1_PlayerOnlineReply_descriptor;
    }

    @java.lang.Override
    public bilibili.app.playeronline.v1.PlayerOnlineReply getDefaultInstanceForType() {
      return bilibili.app.playeronline.v1.PlayerOnlineReply.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.playeronline.v1.PlayerOnlineReply build() {
      bilibili.app.playeronline.v1.PlayerOnlineReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.playeronline.v1.PlayerOnlineReply buildPartial() {
      bilibili.app.playeronline.v1.PlayerOnlineReply result = new bilibili.app.playeronline.v1.PlayerOnlineReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.playeronline.v1.PlayerOnlineReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalText_ = totalText_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.secNext_ = secNext_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bottomShow_ = bottomShow_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sdmShow_ = sdmShow_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sdmText_ = sdmText_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.totalNumber_ = totalNumber_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.totalNumberText_ = totalNumberText_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.playeronline.v1.PlayerOnlineReply) {
        return mergeFrom((bilibili.app.playeronline.v1.PlayerOnlineReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.playeronline.v1.PlayerOnlineReply other) {
      if (other == bilibili.app.playeronline.v1.PlayerOnlineReply.getDefaultInstance()) return this;
      if (!other.getTotalText().isEmpty()) {
        totalText_ = other.totalText_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSecNext() != 0L) {
        setSecNext(other.getSecNext());
      }
      if (other.getBottomShow() != false) {
        setBottomShow(other.getBottomShow());
      }
      if (other.getSdmShow() != false) {
        setSdmShow(other.getSdmShow());
      }
      if (!other.getSdmText().isEmpty()) {
        sdmText_ = other.sdmText_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTotalNumber() != 0L) {
        setTotalNumber(other.getTotalNumber());
      }
      if (!other.getTotalNumberText().isEmpty()) {
        totalNumberText_ = other.totalNumberText_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              totalText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              secNext_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              bottomShow_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              sdmShow_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              sdmText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              totalNumber_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              totalNumberText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object totalText_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_text = 1;</code>
     * @return The totalText.
     */
    public java.lang.String getTotalText() {
      java.lang.Object ref = totalText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_text = 1;</code>
     * @return The bytes for totalText.
     */
    public com.google.protobuf.ByteString
        getTotalTextBytes() {
      java.lang.Object ref = totalText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_text = 1;</code>
     * @param value The totalText to set.
     * @return This builder for chaining.
     */
    public Builder setTotalText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      totalText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalText() {
      totalText_ = getDefaultInstance().getTotalText();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_text = 1;</code>
     * @param value The bytes for totalText to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      totalText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long secNext_ ;
    /**
     * <pre>
     * 下次轮询间隔时间
     * </pre>
     *
     * <code>int64 sec_next = 2;</code>
     * @return The secNext.
     */
    @java.lang.Override
    public long getSecNext() {
      return secNext_;
    }
    /**
     * <pre>
     * 下次轮询间隔时间
     * </pre>
     *
     * <code>int64 sec_next = 2;</code>
     * @param value The secNext to set.
     * @return This builder for chaining.
     */
    public Builder setSecNext(long value) {

      secNext_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 下次轮询间隔时间
     * </pre>
     *
     * <code>int64 sec_next = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecNext() {
      bitField0_ = (bitField0_ & ~0x00000002);
      secNext_ = 0L;
      onChanged();
      return this;
    }

    private boolean bottomShow_ ;
    /**
     * <pre>
     * 是否底部显示
     * </pre>
     *
     * <code>bool bottom_show = 3;</code>
     * @return The bottomShow.
     */
    @java.lang.Override
    public boolean getBottomShow() {
      return bottomShow_;
    }
    /**
     * <pre>
     * 是否底部显示
     * </pre>
     *
     * <code>bool bottom_show = 3;</code>
     * @param value The bottomShow to set.
     * @return This builder for chaining.
     */
    public Builder setBottomShow(boolean value) {

      bottomShow_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否底部显示
     * </pre>
     *
     * <code>bool bottom_show = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBottomShow() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bottomShow_ = false;
      onChanged();
      return this;
    }

    private boolean sdmShow_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>bool sdm_show = 4;</code>
     * @return The sdmShow.
     */
    @java.lang.Override
    public boolean getSdmShow() {
      return sdmShow_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool sdm_show = 4;</code>
     * @param value The sdmShow to set.
     * @return This builder for chaining.
     */
    public Builder setSdmShow(boolean value) {

      sdmShow_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool sdm_show = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSdmShow() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sdmShow_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object sdmText_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string sdm_text = 5;</code>
     * @return The sdmText.
     */
    public java.lang.String getSdmText() {
      java.lang.Object ref = sdmText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdmText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string sdm_text = 5;</code>
     * @return The bytes for sdmText.
     */
    public com.google.protobuf.ByteString
        getSdmTextBytes() {
      java.lang.Object ref = sdmText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdmText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string sdm_text = 5;</code>
     * @param value The sdmText to set.
     * @return This builder for chaining.
     */
    public Builder setSdmText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sdmText_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string sdm_text = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSdmText() {
      sdmText_ = getDefaultInstance().getSdmText();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string sdm_text = 5;</code>
     * @param value The bytes for sdmText to set.
     * @return This builder for chaining.
     */
    public Builder setSdmTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sdmText_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long totalNumber_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 total_number = 6;</code>
     * @return The totalNumber.
     */
    @java.lang.Override
    public long getTotalNumber() {
      return totalNumber_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 total_number = 6;</code>
     * @param value The totalNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTotalNumber(long value) {

      totalNumber_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 total_number = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalNumber() {
      bitField0_ = (bitField0_ & ~0x00000020);
      totalNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object totalNumberText_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_number_text = 7;</code>
     * @return The totalNumberText.
     */
    public java.lang.String getTotalNumberText() {
      java.lang.Object ref = totalNumberText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalNumberText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_number_text = 7;</code>
     * @return The bytes for totalNumberText.
     */
    public com.google.protobuf.ByteString
        getTotalNumberTextBytes() {
      java.lang.Object ref = totalNumberText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalNumberText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_number_text = 7;</code>
     * @param value The totalNumberText to set.
     * @return This builder for chaining.
     */
    public Builder setTotalNumberText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      totalNumberText_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_number_text = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalNumberText() {
      totalNumberText_ = getDefaultInstance().getTotalNumberText();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string total_number_text = 7;</code>
     * @param value The bytes for totalNumberText to set.
     * @return This builder for chaining.
     */
    public Builder setTotalNumberTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      totalNumberText_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.playeronline.v1.PlayerOnlineReply)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.PlayerOnlineReply)
  private static final bilibili.app.playeronline.v1.PlayerOnlineReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.playeronline.v1.PlayerOnlineReply();
  }

  public static bilibili.app.playeronline.v1.PlayerOnlineReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerOnlineReply>
      PARSER = new com.google.protobuf.AbstractParser<PlayerOnlineReply>() {
    @java.lang.Override
    public PlayerOnlineReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerOnlineReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerOnlineReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.playeronline.v1.PlayerOnlineReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

