// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/playershared/playershared.proto

package bilibili.playershared;

/**
 * <pre>
 * 
 * </pre>
 *
 * Protobuf type {@code bilibili.playershared.ConfValue}
 */
public final class ConfValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.playershared.ConfValue)
    ConfValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfValue.newBuilder() to construct.
  private ConfValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfValue() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConfValue();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.playershared.Playershared.internal_static_bilibili_playershared_ConfValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.playershared.Playershared.internal_static_bilibili_playershared_ConfValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.playershared.ConfValue.class, bilibili.playershared.ConfValue.Builder.class);
  }

  private int valueCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SWITCH_VAL(1),
    SELECTED_VAL(2),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 1: return SWITCH_VAL;
        case 2: return SELECTED_VAL;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int SWITCH_VAL_FIELD_NUMBER = 1;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 switch_val = 1;</code>
   * @return Whether the switchVal field is set.
   */
  @java.lang.Override
  public boolean hasSwitchVal() {
    return valueCase_ == 1;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 switch_val = 1;</code>
   * @return The switchVal.
   */
  @java.lang.Override
  public int getSwitchVal() {
    if (valueCase_ == 1) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }

  public static final int SELECTED_VAL_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 selected_val = 2;</code>
   * @return Whether the selectedVal field is set.
   */
  @java.lang.Override
  public boolean hasSelectedVal() {
    return valueCase_ == 2;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 selected_val = 2;</code>
   * @return The selectedVal.
   */
  @java.lang.Override
  public int getSelectedVal() {
    if (valueCase_ == 2) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeInt32(
          1, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 2) {
      output.writeInt32(
          2, (int)((java.lang.Integer) value_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            1, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            2, (int)((java.lang.Integer) value_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.playershared.ConfValue)) {
      return super.equals(obj);
    }
    bilibili.playershared.ConfValue other = (bilibili.playershared.ConfValue) obj;

    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 1:
        if (getSwitchVal()
            != other.getSwitchVal()) return false;
        break;
      case 2:
        if (getSelectedVal()
            != other.getSelectedVal()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valueCase_) {
      case 1:
        hash = (37 * hash) + SWITCH_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getSwitchVal();
        break;
      case 2:
        hash = (37 * hash) + SELECTED_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getSelectedVal();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.playershared.ConfValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.playershared.ConfValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.playershared.ConfValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.playershared.ConfValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bilibili.playershared.ConfValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.playershared.ConfValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.playershared.ConfValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * Protobuf type {@code bilibili.playershared.ConfValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.playershared.ConfValue)
      bilibili.playershared.ConfValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.playershared.Playershared.internal_static_bilibili_playershared_ConfValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.playershared.Playershared.internal_static_bilibili_playershared_ConfValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.playershared.ConfValue.class, bilibili.playershared.ConfValue.Builder.class);
    }

    // Construct using bilibili.playershared.ConfValue.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.playershared.Playershared.internal_static_bilibili_playershared_ConfValue_descriptor;
    }

    @java.lang.Override
    public bilibili.playershared.ConfValue getDefaultInstanceForType() {
      return bilibili.playershared.ConfValue.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.playershared.ConfValue build() {
      bilibili.playershared.ConfValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.playershared.ConfValue buildPartial() {
      bilibili.playershared.ConfValue result = new bilibili.playershared.ConfValue(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.playershared.ConfValue result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(bilibili.playershared.ConfValue result) {
      result.valueCase_ = valueCase_;
      result.value_ = this.value_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.playershared.ConfValue) {
        return mergeFrom((bilibili.playershared.ConfValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.playershared.ConfValue other) {
      if (other == bilibili.playershared.ConfValue.getDefaultInstance()) return this;
      switch (other.getValueCase()) {
        case SWITCH_VAL: {
          setSwitchVal(other.getSwitchVal());
          break;
        }
        case SELECTED_VAL: {
          setSelectedVal(other.getSelectedVal());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              value_ = input.readInt32();
              valueCase_ = 1;
              break;
            } // case 8
            case 16: {
              value_ = input.readInt32();
              valueCase_ = 2;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 switch_val = 1;</code>
     * @return Whether the switchVal field is set.
     */
    public boolean hasSwitchVal() {
      return valueCase_ == 1;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 switch_val = 1;</code>
     * @return The switchVal.
     */
    public int getSwitchVal() {
      if (valueCase_ == 1) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 switch_val = 1;</code>
     * @param value The switchVal to set.
     * @return This builder for chaining.
     */
    public Builder setSwitchVal(int value) {

      valueCase_ = 1;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 switch_val = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSwitchVal() {
      if (valueCase_ == 1) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 selected_val = 2;</code>
     * @return Whether the selectedVal field is set.
     */
    public boolean hasSelectedVal() {
      return valueCase_ == 2;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 selected_val = 2;</code>
     * @return The selectedVal.
     */
    public int getSelectedVal() {
      if (valueCase_ == 2) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 selected_val = 2;</code>
     * @param value The selectedVal to set.
     * @return This builder for chaining.
     */
    public Builder setSelectedVal(int value) {

      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 selected_val = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectedVal() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.playershared.ConfValue)
  }

  // @@protoc_insertion_point(class_scope:bilibili.playershared.ConfValue)
  private static final bilibili.playershared.ConfValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.playershared.ConfValue();
  }

  public static bilibili.playershared.ConfValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfValue>
      PARSER = new com.google.protobuf.AbstractParser<ConfValue>() {
    @java.lang.Override
    public ConfValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConfValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.playershared.ConfValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

