// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/v1/viewunite.proto

package bilibili.app.viewunite.v1;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.v1.OperationCard}
 */
public final class OperationCard extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.v1.OperationCard)
    OperationCardOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OperationCard.newBuilder() to construct.
  private OperationCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OperationCard() {
    bizType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OperationCard();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_OperationCard_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_OperationCard_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.v1.OperationCard.class, bilibili.app.viewunite.v1.OperationCard.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int FROM_FIELD_NUMBER = 2;
  private int from_ = 0;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 from = 2;</code>
   * @return The from.
   */
  @java.lang.Override
  public int getFrom() {
    return from_;
  }

  public static final int TO_FIELD_NUMBER = 3;
  private int to_ = 0;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 to = 3;</code>
   * @return The to.
   */
  @java.lang.Override
  public int getTo() {
    return to_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private boolean status_ = false;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>bool status = 4;</code>
   * @return The status.
   */
  @java.lang.Override
  public boolean getStatus() {
    return status_;
  }

  public static final int BIZ_TYPE_FIELD_NUMBER = 5;
  private int bizType_ = 0;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
   * @return The enum numeric value on the wire for bizType.
   */
  @java.lang.Override public int getBizTypeValue() {
    return bizType_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
   * @return The bizType.
   */
  @java.lang.Override public bilibili.app.viewunite.v1.BizType getBizType() {
    bilibili.app.viewunite.v1.BizType result = bilibili.app.viewunite.v1.BizType.forNumber(bizType_);
    return result == null ? bilibili.app.viewunite.v1.BizType.UNRECOGNIZED : result;
  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private bilibili.app.viewunite.v1.OperationCardContent content_;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return content_ != null;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
   * @return The content.
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.OperationCardContent getContent() {
    return content_ == null ? bilibili.app.viewunite.v1.OperationCardContent.getDefaultInstance() : content_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.OperationCardContentOrBuilder getContentOrBuilder() {
    return content_ == null ? bilibili.app.viewunite.v1.OperationCardContent.getDefaultInstance() : content_;
  }

  public static final int FOLLOW_FIELD_NUMBER = 7;
  private bilibili.app.viewunite.v1.BizFollowVideoParam follow_;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
   * @return Whether the follow field is set.
   */
  @java.lang.Override
  public boolean hasFollow() {
    return follow_ != null;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
   * @return The follow.
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizFollowVideoParam getFollow() {
    return follow_ == null ? bilibili.app.viewunite.v1.BizFollowVideoParam.getDefaultInstance() : follow_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizFollowVideoParamOrBuilder getFollowOrBuilder() {
    return follow_ == null ? bilibili.app.viewunite.v1.BizFollowVideoParam.getDefaultInstance() : follow_;
  }

  public static final int RESERVE_FIELD_NUMBER = 8;
  private bilibili.app.viewunite.v1.BizReserveActivityParam reserve_;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
   * @return Whether the reserve field is set.
   */
  @java.lang.Override
  public boolean hasReserve() {
    return reserve_ != null;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
   * @return The reserve.
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizReserveActivityParam getReserve() {
    return reserve_ == null ? bilibili.app.viewunite.v1.BizReserveActivityParam.getDefaultInstance() : reserve_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizReserveActivityParamOrBuilder getReserveOrBuilder() {
    return reserve_ == null ? bilibili.app.viewunite.v1.BizReserveActivityParam.getDefaultInstance() : reserve_;
  }

  public static final int JUMP_FIELD_NUMBER = 9;
  private bilibili.app.viewunite.v1.BizJumpLinkParam jump_;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
   * @return Whether the jump field is set.
   */
  @java.lang.Override
  public boolean hasJump() {
    return jump_ != null;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
   * @return The jump.
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizJumpLinkParam getJump() {
    return jump_ == null ? bilibili.app.viewunite.v1.BizJumpLinkParam.getDefaultInstance() : jump_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizJumpLinkParamOrBuilder getJumpOrBuilder() {
    return jump_ == null ? bilibili.app.viewunite.v1.BizJumpLinkParam.getDefaultInstance() : jump_;
  }

  public static final int GAME_FIELD_NUMBER = 10;
  private bilibili.app.viewunite.v1.BizReserveGameParam game_;
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
   * @return Whether the game field is set.
   */
  @java.lang.Override
  public boolean hasGame() {
    return game_ != null;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
   * @return The game.
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizReserveGameParam getGame() {
    return game_ == null ? bilibili.app.viewunite.v1.BizReserveGameParam.getDefaultInstance() : game_;
  }
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
   */
  @java.lang.Override
  public bilibili.app.viewunite.v1.BizReserveGameParamOrBuilder getGameOrBuilder() {
    return game_ == null ? bilibili.app.viewunite.v1.BizReserveGameParam.getDefaultInstance() : game_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (from_ != 0) {
      output.writeInt32(2, from_);
    }
    if (to_ != 0) {
      output.writeInt32(3, to_);
    }
    if (status_ != false) {
      output.writeBool(4, status_);
    }
    if (bizType_ != bilibili.app.viewunite.v1.BizType.BizTypeNone.getNumber()) {
      output.writeEnum(5, bizType_);
    }
    if (content_ != null) {
      output.writeMessage(6, getContent());
    }
    if (follow_ != null) {
      output.writeMessage(7, getFollow());
    }
    if (reserve_ != null) {
      output.writeMessage(8, getReserve());
    }
    if (jump_ != null) {
      output.writeMessage(9, getJump());
    }
    if (game_ != null) {
      output.writeMessage(10, getGame());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (from_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, from_);
    }
    if (to_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, to_);
    }
    if (status_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, status_);
    }
    if (bizType_ != bilibili.app.viewunite.v1.BizType.BizTypeNone.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, bizType_);
    }
    if (content_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getContent());
    }
    if (follow_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getFollow());
    }
    if (reserve_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getReserve());
    }
    if (jump_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getJump());
    }
    if (game_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getGame());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.v1.OperationCard)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.v1.OperationCard other = (bilibili.app.viewunite.v1.OperationCard) obj;

    if (getId()
        != other.getId()) return false;
    if (getFrom()
        != other.getFrom()) return false;
    if (getTo()
        != other.getTo()) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (bizType_ != other.bizType_) return false;
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (hasFollow() != other.hasFollow()) return false;
    if (hasFollow()) {
      if (!getFollow()
          .equals(other.getFollow())) return false;
    }
    if (hasReserve() != other.hasReserve()) return false;
    if (hasReserve()) {
      if (!getReserve()
          .equals(other.getReserve())) return false;
    }
    if (hasJump() != other.hasJump()) return false;
    if (hasJump()) {
      if (!getJump()
          .equals(other.getJump())) return false;
    }
    if (hasGame() != other.hasGame()) return false;
    if (hasGame()) {
      if (!getGame()
          .equals(other.getGame())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStatus());
    hash = (37 * hash) + BIZ_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + bizType_;
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    if (hasFollow()) {
      hash = (37 * hash) + FOLLOW_FIELD_NUMBER;
      hash = (53 * hash) + getFollow().hashCode();
    }
    if (hasReserve()) {
      hash = (37 * hash) + RESERVE_FIELD_NUMBER;
      hash = (53 * hash) + getReserve().hashCode();
    }
    if (hasJump()) {
      hash = (37 * hash) + JUMP_FIELD_NUMBER;
      hash = (53 * hash) + getJump().hashCode();
    }
    if (hasGame()) {
      hash = (37 * hash) + GAME_FIELD_NUMBER;
      hash = (53 * hash) + getGame().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.v1.OperationCard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.v1.OperationCard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.v1.OperationCard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.v1.OperationCard)
      bilibili.app.viewunite.v1.OperationCardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_OperationCard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_OperationCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.v1.OperationCard.class, bilibili.app.viewunite.v1.OperationCard.Builder.class);
    }

    // Construct using bilibili.app.viewunite.v1.OperationCard.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      from_ = 0;
      to_ = 0;
      status_ = false;
      bizType_ = 0;
      content_ = null;
      if (contentBuilder_ != null) {
        contentBuilder_.dispose();
        contentBuilder_ = null;
      }
      follow_ = null;
      if (followBuilder_ != null) {
        followBuilder_.dispose();
        followBuilder_ = null;
      }
      reserve_ = null;
      if (reserveBuilder_ != null) {
        reserveBuilder_.dispose();
        reserveBuilder_ = null;
      }
      jump_ = null;
      if (jumpBuilder_ != null) {
        jumpBuilder_.dispose();
        jumpBuilder_ = null;
      }
      game_ = null;
      if (gameBuilder_ != null) {
        gameBuilder_.dispose();
        gameBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_OperationCard_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.OperationCard getDefaultInstanceForType() {
      return bilibili.app.viewunite.v1.OperationCard.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.OperationCard build() {
      bilibili.app.viewunite.v1.OperationCard result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.OperationCard buildPartial() {
      bilibili.app.viewunite.v1.OperationCard result = new bilibili.app.viewunite.v1.OperationCard(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.v1.OperationCard result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.from_ = from_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.to_ = to_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bizType_ = bizType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.content_ = contentBuilder_ == null
            ? content_
            : contentBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.follow_ = followBuilder_ == null
            ? follow_
            : followBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.reserve_ = reserveBuilder_ == null
            ? reserve_
            : reserveBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.jump_ = jumpBuilder_ == null
            ? jump_
            : jumpBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.game_ = gameBuilder_ == null
            ? game_
            : gameBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.v1.OperationCard) {
        return mergeFrom((bilibili.app.viewunite.v1.OperationCard)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.v1.OperationCard other) {
      if (other == bilibili.app.viewunite.v1.OperationCard.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getFrom() != 0) {
        setFrom(other.getFrom());
      }
      if (other.getTo() != 0) {
        setTo(other.getTo());
      }
      if (other.getStatus() != false) {
        setStatus(other.getStatus());
      }
      if (other.bizType_ != 0) {
        setBizTypeValue(other.getBizTypeValue());
      }
      if (other.hasContent()) {
        mergeContent(other.getContent());
      }
      if (other.hasFollow()) {
        mergeFollow(other.getFollow());
      }
      if (other.hasReserve()) {
        mergeReserve(other.getReserve());
      }
      if (other.hasJump()) {
        mergeJump(other.getJump());
      }
      if (other.hasGame()) {
        mergeGame(other.getGame());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              from_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              to_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              status_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              bizType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getContentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getFollowFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getReserveFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getJumpFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getGameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int from_ ;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 from = 2;</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 from = 2;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(int value) {

      from_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 from = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000002);
      from_ = 0;
      onChanged();
      return this;
    }

    private int to_ ;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public int getTo() {
      return to_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 to = 3;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(int value) {

      to_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 to = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      to_ = 0;
      onChanged();
      return this;
    }

    private boolean status_ ;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>bool status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public boolean getStatus() {
      return status_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>bool status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(boolean value) {

      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>bool status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = false;
      onChanged();
      return this;
    }

    private int bizType_ = 0;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
     * @return The enum numeric value on the wire for bizType.
     */
    @java.lang.Override public int getBizTypeValue() {
      return bizType_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
     * @param value The enum numeric value on the wire for bizType to set.
     * @return This builder for chaining.
     */
    public Builder setBizTypeValue(int value) {
      bizType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
     * @return The bizType.
     */
    @java.lang.Override
    public bilibili.app.viewunite.v1.BizType getBizType() {
      bilibili.app.viewunite.v1.BizType result = bilibili.app.viewunite.v1.BizType.forNumber(bizType_);
      return result == null ? bilibili.app.viewunite.v1.BizType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
     * @param value The bizType to set.
     * @return This builder for chaining.
     */
    public Builder setBizType(bilibili.app.viewunite.v1.BizType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      bizType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizType biz_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBizType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bizType_ = 0;
      onChanged();
      return this;
    }

    private bilibili.app.viewunite.v1.OperationCardContent content_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.OperationCardContent, bilibili.app.viewunite.v1.OperationCardContent.Builder, bilibili.app.viewunite.v1.OperationCardContentOrBuilder> contentBuilder_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     * @return The content.
     */
    public bilibili.app.viewunite.v1.OperationCardContent getContent() {
      if (contentBuilder_ == null) {
        return content_ == null ? bilibili.app.viewunite.v1.OperationCardContent.getDefaultInstance() : content_;
      } else {
        return contentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public Builder setContent(bilibili.app.viewunite.v1.OperationCardContent value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
      } else {
        contentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public Builder setContent(
        bilibili.app.viewunite.v1.OperationCardContent.Builder builderForValue) {
      if (contentBuilder_ == null) {
        content_ = builderForValue.build();
      } else {
        contentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public Builder mergeContent(bilibili.app.viewunite.v1.OperationCardContent value) {
      if (contentBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          content_ != null &&
          content_ != bilibili.app.viewunite.v1.OperationCardContent.getDefaultInstance()) {
          getContentBuilder().mergeFrom(value);
        } else {
          content_ = value;
        }
      } else {
        contentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      content_ = null;
      if (contentBuilder_ != null) {
        contentBuilder_.dispose();
        contentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public bilibili.app.viewunite.v1.OperationCardContent.Builder getContentBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getContentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    public bilibili.app.viewunite.v1.OperationCardContentOrBuilder getContentOrBuilder() {
      if (contentBuilder_ != null) {
        return contentBuilder_.getMessageOrBuilder();
      } else {
        return content_ == null ?
            bilibili.app.viewunite.v1.OperationCardContent.getDefaultInstance() : content_;
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.OperationCardContent content = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.OperationCardContent, bilibili.app.viewunite.v1.OperationCardContent.Builder, bilibili.app.viewunite.v1.OperationCardContentOrBuilder> 
        getContentFieldBuilder() {
      if (contentBuilder_ == null) {
        contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.viewunite.v1.OperationCardContent, bilibili.app.viewunite.v1.OperationCardContent.Builder, bilibili.app.viewunite.v1.OperationCardContentOrBuilder>(
                getContent(),
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      return contentBuilder_;
    }

    private bilibili.app.viewunite.v1.BizFollowVideoParam follow_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizFollowVideoParam, bilibili.app.viewunite.v1.BizFollowVideoParam.Builder, bilibili.app.viewunite.v1.BizFollowVideoParamOrBuilder> followBuilder_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     * @return Whether the follow field is set.
     */
    public boolean hasFollow() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     * @return The follow.
     */
    public bilibili.app.viewunite.v1.BizFollowVideoParam getFollow() {
      if (followBuilder_ == null) {
        return follow_ == null ? bilibili.app.viewunite.v1.BizFollowVideoParam.getDefaultInstance() : follow_;
      } else {
        return followBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public Builder setFollow(bilibili.app.viewunite.v1.BizFollowVideoParam value) {
      if (followBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        follow_ = value;
      } else {
        followBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public Builder setFollow(
        bilibili.app.viewunite.v1.BizFollowVideoParam.Builder builderForValue) {
      if (followBuilder_ == null) {
        follow_ = builderForValue.build();
      } else {
        followBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public Builder mergeFollow(bilibili.app.viewunite.v1.BizFollowVideoParam value) {
      if (followBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          follow_ != null &&
          follow_ != bilibili.app.viewunite.v1.BizFollowVideoParam.getDefaultInstance()) {
          getFollowBuilder().mergeFrom(value);
        } else {
          follow_ = value;
        }
      } else {
        followBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public Builder clearFollow() {
      bitField0_ = (bitField0_ & ~0x00000040);
      follow_ = null;
      if (followBuilder_ != null) {
        followBuilder_.dispose();
        followBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public bilibili.app.viewunite.v1.BizFollowVideoParam.Builder getFollowBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getFollowFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    public bilibili.app.viewunite.v1.BizFollowVideoParamOrBuilder getFollowOrBuilder() {
      if (followBuilder_ != null) {
        return followBuilder_.getMessageOrBuilder();
      } else {
        return follow_ == null ?
            bilibili.app.viewunite.v1.BizFollowVideoParam.getDefaultInstance() : follow_;
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizFollowVideoParam follow = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizFollowVideoParam, bilibili.app.viewunite.v1.BizFollowVideoParam.Builder, bilibili.app.viewunite.v1.BizFollowVideoParamOrBuilder> 
        getFollowFieldBuilder() {
      if (followBuilder_ == null) {
        followBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.viewunite.v1.BizFollowVideoParam, bilibili.app.viewunite.v1.BizFollowVideoParam.Builder, bilibili.app.viewunite.v1.BizFollowVideoParamOrBuilder>(
                getFollow(),
                getParentForChildren(),
                isClean());
        follow_ = null;
      }
      return followBuilder_;
    }

    private bilibili.app.viewunite.v1.BizReserveActivityParam reserve_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizReserveActivityParam, bilibili.app.viewunite.v1.BizReserveActivityParam.Builder, bilibili.app.viewunite.v1.BizReserveActivityParamOrBuilder> reserveBuilder_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     * @return Whether the reserve field is set.
     */
    public boolean hasReserve() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     * @return The reserve.
     */
    public bilibili.app.viewunite.v1.BizReserveActivityParam getReserve() {
      if (reserveBuilder_ == null) {
        return reserve_ == null ? bilibili.app.viewunite.v1.BizReserveActivityParam.getDefaultInstance() : reserve_;
      } else {
        return reserveBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public Builder setReserve(bilibili.app.viewunite.v1.BizReserveActivityParam value) {
      if (reserveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reserve_ = value;
      } else {
        reserveBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public Builder setReserve(
        bilibili.app.viewunite.v1.BizReserveActivityParam.Builder builderForValue) {
      if (reserveBuilder_ == null) {
        reserve_ = builderForValue.build();
      } else {
        reserveBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public Builder mergeReserve(bilibili.app.viewunite.v1.BizReserveActivityParam value) {
      if (reserveBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          reserve_ != null &&
          reserve_ != bilibili.app.viewunite.v1.BizReserveActivityParam.getDefaultInstance()) {
          getReserveBuilder().mergeFrom(value);
        } else {
          reserve_ = value;
        }
      } else {
        reserveBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public Builder clearReserve() {
      bitField0_ = (bitField0_ & ~0x00000080);
      reserve_ = null;
      if (reserveBuilder_ != null) {
        reserveBuilder_.dispose();
        reserveBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public bilibili.app.viewunite.v1.BizReserveActivityParam.Builder getReserveBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getReserveFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    public bilibili.app.viewunite.v1.BizReserveActivityParamOrBuilder getReserveOrBuilder() {
      if (reserveBuilder_ != null) {
        return reserveBuilder_.getMessageOrBuilder();
      } else {
        return reserve_ == null ?
            bilibili.app.viewunite.v1.BizReserveActivityParam.getDefaultInstance() : reserve_;
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveActivityParam reserve = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizReserveActivityParam, bilibili.app.viewunite.v1.BizReserveActivityParam.Builder, bilibili.app.viewunite.v1.BizReserveActivityParamOrBuilder> 
        getReserveFieldBuilder() {
      if (reserveBuilder_ == null) {
        reserveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.viewunite.v1.BizReserveActivityParam, bilibili.app.viewunite.v1.BizReserveActivityParam.Builder, bilibili.app.viewunite.v1.BizReserveActivityParamOrBuilder>(
                getReserve(),
                getParentForChildren(),
                isClean());
        reserve_ = null;
      }
      return reserveBuilder_;
    }

    private bilibili.app.viewunite.v1.BizJumpLinkParam jump_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizJumpLinkParam, bilibili.app.viewunite.v1.BizJumpLinkParam.Builder, bilibili.app.viewunite.v1.BizJumpLinkParamOrBuilder> jumpBuilder_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     * @return Whether the jump field is set.
     */
    public boolean hasJump() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     * @return The jump.
     */
    public bilibili.app.viewunite.v1.BizJumpLinkParam getJump() {
      if (jumpBuilder_ == null) {
        return jump_ == null ? bilibili.app.viewunite.v1.BizJumpLinkParam.getDefaultInstance() : jump_;
      } else {
        return jumpBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public Builder setJump(bilibili.app.viewunite.v1.BizJumpLinkParam value) {
      if (jumpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jump_ = value;
      } else {
        jumpBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public Builder setJump(
        bilibili.app.viewunite.v1.BizJumpLinkParam.Builder builderForValue) {
      if (jumpBuilder_ == null) {
        jump_ = builderForValue.build();
      } else {
        jumpBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public Builder mergeJump(bilibili.app.viewunite.v1.BizJumpLinkParam value) {
      if (jumpBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          jump_ != null &&
          jump_ != bilibili.app.viewunite.v1.BizJumpLinkParam.getDefaultInstance()) {
          getJumpBuilder().mergeFrom(value);
        } else {
          jump_ = value;
        }
      } else {
        jumpBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public Builder clearJump() {
      bitField0_ = (bitField0_ & ~0x00000100);
      jump_ = null;
      if (jumpBuilder_ != null) {
        jumpBuilder_.dispose();
        jumpBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public bilibili.app.viewunite.v1.BizJumpLinkParam.Builder getJumpBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getJumpFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    public bilibili.app.viewunite.v1.BizJumpLinkParamOrBuilder getJumpOrBuilder() {
      if (jumpBuilder_ != null) {
        return jumpBuilder_.getMessageOrBuilder();
      } else {
        return jump_ == null ?
            bilibili.app.viewunite.v1.BizJumpLinkParam.getDefaultInstance() : jump_;
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizJumpLinkParam jump = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizJumpLinkParam, bilibili.app.viewunite.v1.BizJumpLinkParam.Builder, bilibili.app.viewunite.v1.BizJumpLinkParamOrBuilder> 
        getJumpFieldBuilder() {
      if (jumpBuilder_ == null) {
        jumpBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.viewunite.v1.BizJumpLinkParam, bilibili.app.viewunite.v1.BizJumpLinkParam.Builder, bilibili.app.viewunite.v1.BizJumpLinkParamOrBuilder>(
                getJump(),
                getParentForChildren(),
                isClean());
        jump_ = null;
      }
      return jumpBuilder_;
    }

    private bilibili.app.viewunite.v1.BizReserveGameParam game_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizReserveGameParam, bilibili.app.viewunite.v1.BizReserveGameParam.Builder, bilibili.app.viewunite.v1.BizReserveGameParamOrBuilder> gameBuilder_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     * @return Whether the game field is set.
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     * @return The game.
     */
    public bilibili.app.viewunite.v1.BizReserveGameParam getGame() {
      if (gameBuilder_ == null) {
        return game_ == null ? bilibili.app.viewunite.v1.BizReserveGameParam.getDefaultInstance() : game_;
      } else {
        return gameBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public Builder setGame(bilibili.app.viewunite.v1.BizReserveGameParam value) {
      if (gameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        game_ = value;
      } else {
        gameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public Builder setGame(
        bilibili.app.viewunite.v1.BizReserveGameParam.Builder builderForValue) {
      if (gameBuilder_ == null) {
        game_ = builderForValue.build();
      } else {
        gameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public Builder mergeGame(bilibili.app.viewunite.v1.BizReserveGameParam value) {
      if (gameBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          game_ != null &&
          game_ != bilibili.app.viewunite.v1.BizReserveGameParam.getDefaultInstance()) {
          getGameBuilder().mergeFrom(value);
        } else {
          game_ = value;
        }
      } else {
        gameBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public Builder clearGame() {
      bitField0_ = (bitField0_ & ~0x00000200);
      game_ = null;
      if (gameBuilder_ != null) {
        gameBuilder_.dispose();
        gameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public bilibili.app.viewunite.v1.BizReserveGameParam.Builder getGameBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getGameFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    public bilibili.app.viewunite.v1.BizReserveGameParamOrBuilder getGameOrBuilder() {
      if (gameBuilder_ != null) {
        return gameBuilder_.getMessageOrBuilder();
      } else {
        return game_ == null ?
            bilibili.app.viewunite.v1.BizReserveGameParam.getDefaultInstance() : game_;
      }
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>.bilibili.app.viewunite.v1.BizReserveGameParam game = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bilibili.app.viewunite.v1.BizReserveGameParam, bilibili.app.viewunite.v1.BizReserveGameParam.Builder, bilibili.app.viewunite.v1.BizReserveGameParamOrBuilder> 
        getGameFieldBuilder() {
      if (gameBuilder_ == null) {
        gameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bilibili.app.viewunite.v1.BizReserveGameParam, bilibili.app.viewunite.v1.BizReserveGameParam.Builder, bilibili.app.viewunite.v1.BizReserveGameParamOrBuilder>(
                getGame(),
                getParentForChildren(),
                isClean());
        game_ = null;
      }
      return gameBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.v1.OperationCard)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.v1.OperationCard)
  private static final bilibili.app.viewunite.v1.OperationCard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.v1.OperationCard();
  }

  public static bilibili.app.viewunite.v1.OperationCard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperationCard>
      PARSER = new com.google.protobuf.AbstractParser<OperationCard>() {
    @java.lang.Override
    public OperationCard parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OperationCard> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperationCard> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.v1.OperationCard getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

