// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/listener/v1/listener.proto

package bilibili.app.listener.v1;

public interface PageOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.listener.v1.PageOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>int32 page_size = 1;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * </pre>
   *
   * <code>int32 direction = 2;</code>
   * @return The direction.
   */
  int getDirection();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.listener.v1.PlayItem last_item = 3;</code>
   * @return Whether the lastItem field is set.
   */
  boolean hasLastItem();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.listener.v1.PlayItem last_item = 3;</code>
   * @return The lastItem.
   */
  bilibili.app.listener.v1.PlayItem getLastItem();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.listener.v1.PlayItem last_item = 3;</code>
   */
  bilibili.app.listener.v1.PlayItemOrBuilder getLastItemOrBuilder();
}
