// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/account/fission/v1/fission.proto

package bilibili.account.fission.v1;

public interface WindowReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.account.fission.v1.WindowReq)
    com.google.protobuf.MessageOrBuilder {
}
