// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v1/playurl.proto

package bilibili.pgc.gateway.player.v1;

public interface RoomShowInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.pgc.gateway.player.v1.RoomShowInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 短号
   * </pre>
   *
   * <code>int64 short_id = 1;</code>
   * @return The shortId.
   */
  long getShortId();

  /**
   * <pre>
   * 人气值
   * </pre>
   *
   * <code>int64 popularity_count = 8;</code>
   * @return The popularityCount.
   */
  long getPopularityCount();

  /**
   * <pre>
   * 最近一次开播时间戳
   * </pre>
   *
   * <code>int64 live_start_time = 10;</code>
   * @return The liveStartTime.
   */
  long getLiveStartTime();
}
