// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/polymer/app/search/v1/search.proto

package bilibili.polymer.app.search.v1;

public interface BrandADAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.polymer.app.search.v1.BrandADAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>string param = 1;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <pre>
   * </pre>
   *
   * <code>string param = 1;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>string goto = 2;</code>
   * @return The goto.
   */
  java.lang.String getGoto();
  /**
   * <pre>
   * </pre>
   *
   * <code>string goto = 2;</code>
   * @return The bytes for goto.
   */
  com.google.protobuf.ByteString
      getGotoBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 mid = 3;</code>
   * @return The mid.
   */
  long getMid();

  /**
   * <pre>
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>string face = 5;</code>
   * @return The face.
   */
  java.lang.String getFace();
  /**
   * <pre>
   * </pre>
   *
   * <code>string face = 5;</code>
   * @return The bytes for face.
   */
  com.google.protobuf.ByteString
      getFaceBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>string sign = 6;</code>
   * @return The sign.
   */
  java.lang.String getSign();
  /**
   * <pre>
   * </pre>
   *
   * <code>string sign = 6;</code>
   * @return The bytes for sign.
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.Relation relation = 7;</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.Relation relation = 7;</code>
   * @return The relation.
   */
  bilibili.polymer.app.search.v1.Relation getRelation();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.Relation relation = 7;</code>
   */
  bilibili.polymer.app.search.v1.RelationOrBuilder getRelationOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 roomid = 8;</code>
   * @return The roomid.
   */
  long getRoomid();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 live_status = 9;</code>
   * @return The liveStatus.
   */
  long getLiveStatus();

  /**
   * <pre>
   * </pre>
   *
   * <code>string live_link = 10;</code>
   * @return The liveLink.
   */
  java.lang.String getLiveLink();
  /**
   * <pre>
   * </pre>
   *
   * <code>string live_link = 10;</code>
   * @return The bytes for liveLink.
   */
  com.google.protobuf.ByteString
      getLiveLinkBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.OfficialVerify official_verify = 11;</code>
   * @return Whether the officialVerify field is set.
   */
  boolean hasOfficialVerify();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.OfficialVerify official_verify = 11;</code>
   * @return The officialVerify.
   */
  bilibili.polymer.app.search.v1.OfficialVerify getOfficialVerify();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.OfficialVerify official_verify = 11;</code>
   */
  bilibili.polymer.app.search.v1.OfficialVerifyOrBuilder getOfficialVerifyOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.VipInfo vip = 12;</code>
   * @return Whether the vip field is set.
   */
  boolean hasVip();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.VipInfo vip = 12;</code>
   * @return The vip.
   */
  bilibili.polymer.app.search.v1.VipInfo getVip();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.polymer.app.search.v1.VipInfo vip = 12;</code>
   */
  bilibili.polymer.app.search.v1.VipInfoOrBuilder getVipOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>string uri = 13;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * </pre>
   *
   * <code>string uri = 13;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>int32 face_nft_new = 14;</code>
   * @return The faceNftNew.
   */
  int getFaceNftNew();
}
